### PR TITLE
(Fix #22) Upgrade boto to boto3

### LINKED ISSUE #22: Outdated boto lib version?
Hi!

I'm trying to read config file from versioned encrypted with default S3 KMS key S3 bucket
Getting the following

```
Traceback (most recent call last):
  File "/opt/bin/config.py", line 329, in <module>
    main()
  File "/opt/bin/config.py", line 313, in main
    data = gather_user_data_s3(sys.argv[1])
  File "/opt/bin/config.py", line 183, in gather_user_data_s3
    data = key.get_contents_as_string()
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1782, in get_contents_as_string
    response_headers=response_headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1650, in get_contents_to_file
    response_headers=response_headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1482, in get_file
    query_args=None)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1514, in _get_file_internal
    override_num_retries=override_num_retries)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 343, in open
    override_num_retries=override_num_retries)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 303, in open_read
    self.resp.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>null</ArgumentValue><RequestId>39026ABA876B2920</RequestId><HostId>a2LDcGwluokuBqs0jFo74cVNbo3wwOSlk5gz8InztUXObGoG7fRSScF4a7R97gEYyRdYf23tjpA=</HostId></Error>
```

After playing around with code it seems that the old version of boto isn't working

Updating function to use boto3 solves that (see working code below)

```
def gather_user_data_s3(s3_url):
    import boto3

    parts = urlparse(s3_url)

    if parts.scheme != 's3':
        raise Exception("Must use s3 url scheme")

    bucket_name = parts.netloc
    path = parts.path.lstrip('/')

    s3 = boto3.resource('s3')
    obj = s3.Object(bucket_name, path)
    data = obj.get()['Body'].read().decode('utf-8')

    return json.loads(data)
```

Shall I do a pull request or what is contribution procedure?

### PR DESCRIPTION
**Pull request by Andrey9kin**
See issue #22 for more details

### CODE REVIEW

**Comment by Andrey9kin** [comment]
@ttheune here you go

**Comment by ttheune** [comment]
Thanks, we'll get this tested out Monday.

**Comment by Andrey9kin** [comment]
@ttheune any luck?

**Comment by ttheune** [comment]
Sorry for the delay, we still need to get this tested.  I'll update asap.

**Pull request merged**
